### ISSUE TITLE
Provide instructions on setting execution policy

### ISSUE THREAD

**Issue by never147** [shupershuff/Diablo2RLoader#1]
When the script is ran for the first time on my machine I get an error

```
PS D:\Users\m\Desktop\Diablo2RLoader\Diablo2RLoader-main> .\D2Loader.ps1
.\D2Loader.ps1 : File D:\Users\m\Desktop\Diablo2RLoader\Diablo2RLoader-main\D2Loader.ps1 cannot be loaded because
running scripts is disabled on this system. For more information, see about_Execution_Policies at
https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ .\D2Loader.ps1
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
```

I can set the permission like so, but it seems like a potential risk.

```
PS D:\Users\m\Desktop\Diablo2RLoader\Diablo2RLoader-main> Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope CurrentUser
```

Following this, there is a message

```
PS D:\Users\m\Desktop\Diablo2RLoader\Diablo2RLoader-main> .\D2Loader.ps1

Security warning
Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your
computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning
message. Do you want to run D:\Users\m\Desktop\Diablo2RLoader\Diablo2RLoader-main\D2Loader.ps1?
[D] Do not run  [R] Run once  [S] Suspend  [?] Help (default is "D"):
```

Perhaps the README.md should contain advice on how to configure this? Possibly with a safe config or a warning

**Comment by shupershuff** [comment]
Thanks for notifying me on this. I had chucked in a parameter "-ExecutionPolicy Bypass" but obviously that alone isn't working. Will investigate tonight and update the readme if any additional instructions are required to run this.

In the mean time I believe right clicking on the script, opening properties and checking the "unblock" box should help alleviate these issues.

**Comment by shupershuff** [comment]
Two issues at play here, neither of which can be addressed within a script.
1. User machines will likely have an execution policy set to restricted (as per [this](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.3). As such they'll need to manually change this to "remote signed" as a one off task.
2. Files downloaded from the internet need to be unblocked within properties before they can properly be used (this is the same as when you download word/excel docs or anything really). Instructions added, but if skipped script will prompt once to do this (no edits made here, this is powershell default behaviour)

Instructions updated
