### ISSUE TITLE
Format Exception in Line 199

### ISSUE THREAD

**Issue by bmml1** [shupershuff/Diablo2RLoader#16]
Hello,

the if clause in line 199 throws an exception which might have something to do with locales. I am using Windows 11 with german system locale. Script continues just fine, but the auto update column in stats does not get updated in the stats.csv due to the exception.

It says something like "the string is not a valid datetime"

![exception](https://github.com/shupershuff/Diablo2RLoader/assets/32018487/9aadef65-cfcf-44d6-9fd3-04b2cd33278b)

To reproduce I did this:

![exception2](https://github.com/shupershuff/Diablo2RLoader/assets/32018487/65792305-36c3-4c0f-87e7-0c2d709f6ba6)

Cheers!

**Comment by shupershuff** [comment]
Gutentag!
Yes the issue was the time variable couldn't be converted if DD was a single digit.
Meaning if you ran it on the 1st through to the 9th of the month it would crap out. This breaks the update checker. Pretty annoying and not something I tested for before releasing.

Fix is to either manually update to latest version or open stats.csv and delete the value for LastUpdateCheck.
Also covered off here: https://github.com/shupershuff/Diablo2RLoader/issues/15

I'll put a note on the readme page too.

**Comment by bmml1** [comment]
Hello,

thanks for the quick response. I still have the issue with 1.83

What happens if you test the part from screenshot 2 in your powershell console?

BR

**Comment by bmml1** [comment]
These two variants would work on my machine. Maybe you can try on yours too
 
```
[datetime]::ParseExact('3/6/2000 12:00:00 PM','d/M/yyyy h:mm:ss tt', [cultureinfo]::InvariantCulture)
Samstag, 3. Juni 2000 12:00:00
```

```
[datetime]::ParseExact('03/06/2000 12:00:00 PM','d/M/yyyy h:mm:ss tt', [cultureinfo]::InvariantCulture)
Samstag, 3. Juni 2000 12:00:00
```

**Comment by shupershuff** [comment]
> Hello,
> 
> thanks for the quick response. I still have the issue with 1.83
> 
> What happens if you test the part from screenshot 2 in your powershell console?
> 
> BR

I tried the below which worked fine for me:
```
$s = "28/06/2000 12:00:00 pm"
[DateTime]::ParseExact($s, "dd/MM/yyyy h:mm:ss tt", $null);
```
![image](https://github.com/shupershuff/Diablo2RLoader/assets/63577525/e6233580-0e10-4b30-aced-5e3802972c99)

I suspect the issue is with having different region settings. What do your date settings look like? Mine look like this. I might use your suggestion with Universal time.
![image](https://github.com/shupershuff/Diablo2RLoader/assets/63577525/1b63a18c-931d-4cec-a02c-2e564476fd3c)

**Comment by shupershuff** [comment]
@bmml1 Can you test this for me:

```
$s = [Datetime]"28/06/2000 12:00:00 pm"
[DateTime]::ParseExact($s, "dd/MM/yyyy h:mm:ss tt", $null);
```

**Comment by bmml1** [comment]
Does not work, most likely because of locale settings.
```
PS C:\Users\xx> $s = [Datetime]"28/06/2000 12:00:00 pm"
Der Wert "28/06/2000 12:00:00 pm" kann nicht in den Typ "System.DateTime" konvertiert werden. Fehler: "Die
Zeichenfolge wurde nicht als gültiges DateTime erkannt."
In Zeile:1 Zeichen:1
+ $s = [Datetime]"28/06/2000 12:00:00 pm"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
```

Here are mine:
![grafik](https://github.com/shupershuff/Diablo2RLoader/assets/32018487/2a31ab07-c33a-4bdf-92bd-4a6d8cf84599)

**Comment by shupershuff** [comment]
Thanks, I'll try and update the script to use universal time tonight.

**Comment by shupershuff** [comment]
I've done a slightly different approach, this time specifying how to read the data as well as how to output it.
Can please ask you to test this for me before I release this?
Please test by downloading the updated PS1 file and copy over your existing one. You won't have to edit stats.csv.
https://github.com/shupershuff/Diablo2RLoader/blob/main/D2Loader.ps1

**Comment by bmml1** [comment]
Works like a charm. Thx :)

**Comment by never147** [comment]
Ha I was just looking at this as I was still getting an error. I thought I'd try to fix it myself. Tried to push and saw you fixed it too! I did it really similarly

```
$CurrentStats.LastUpdateCheck = get-date -Format "dd/MM/yyyy hh:mm:ss"
```

removed the `pm` where it's written.

**Comment by shupershuff** [comment]
I made a couple other slight changes prior to release but it's functionally the same. 
Thanks for raising this and thanks for your input.

**Comment by shupershuff** [comment]
@bmml1 have you had any issues the hours played display showing incorrectly? Wondering if there's another regional issue.

Just had another German based person note that the display shows incorrectly (possibly minutes showing as hours):
![image](https://github.com/shupershuff/Diablo2RLoader/assets/63577525/ce065341-a17d-4274-8d0a-d21de40d727b)

It should look like this
![image](https://github.com/shupershuff/Diablo2RLoader/assets/63577525/8df81c15-3b8d-4015-9c46-4c1329df16c5)

**Comment by bmml1** [comment]
Yep, looks like in the first picture.

**Comment by shupershuff** [comment]
I've drafted a small update to resolve that issue. If you like you can test it:
https://github.com/shupershuff/Diablo2RLoader/blob/main/D2Loader.ps1

**Comment by bmml1** [comment]
Now it looks like in picture 2. thx
