### ISSUE TITLE
stopped working

### ISSUE THREAD

**Issue by subaridji** [shupershuff/Diablo2RLoader#17]
smth's wrong in $arguments, can't debug.
accounts.csv string looks like this:
```
1,acc@mail.com,Main,,,pwd!,,-enablerespec -txt -mod mod
``` 
the game is being launched and renamed but somehow 'connecting to battlenet' screen is being skipped and i'm being thrown on offline characters tab. switching to online tab results in 'cannot connect to server' dialog.
same options given via shortcut work like a charm:
```
gamepath\D2R.exe -username acc@mail.com -password pwd! -address eu.actual.battle.net -enablerespec -txt -mod mod
``` 
tested with or without password encryption and timetracking - no difference

**Comment by subaridji** [comment]
**figured out:**
apparently after some failed login attempts battle.net enables captcha protection for autherization.

in this case autherization within command line arguments stops working at all. the only way to login remains only through passing captcha and launching game from bnet client.

problem resolves itself when captcha is disabled after some time (6h in my case).

no issues in code, maybe just +1 topic in faq\readme

**Comment by shupershuff** [comment]
Thanks for raising this.
I'll leave this open until I get a moment to update the FAQ.
