### ISSUE TITLE
Cant verify your account error

### ISSUE THREAD

**Issue by Hotorr** [shupershuff/Diablo2RLoader#18]
Hello I've set up the launcher and it works fine. But when I add a 4th account it always puts me the msg cant verify your account with that information I double checked if I typed everything correct but even after double checking I cant find the issue.

**Comment by shupershuff** [comment]
Does the 4th account have Multi Factor authentication available?

Unfortunately the method of opening d2r.exe and passing Username and PW params to it doesn't work for 2FA.

If not, try opening the account with the battlenet client, it might be wanting you to enter a captcha code.

**Comment by Hotorr** [comment]
No I do not, that's what I thought so as well but even when I do it I still
get the same error message. It could be definitely the captcha but for some
reason it constantly asks for it. Even when I switched my pc just to try
the fresh account I still get the same message

čet, 14. ruj 2023. u 00:58 shupershuff ***@***.***> napisao
je:

**Comment by Hotorr** [comment]
No I do not, that's what I thought so as well but even when I do it I still get the same error message. It could be definitely the captcha but for some reason it constantly asks for it. Even when I switched my pc just to try the fresh account I still get the same message

**Comment by shupershuff** [comment]
What are the exact words of the error?
If it's along the lines of "cant verify your account" as you've stated, it's likely due to captcha or simply you haven't completed the account verification (check your email for that account).

If it's along the lines of "Problem authenticating your account" then it will be because you've entered the username or  password incorrectly.

**Comment by Hotorr** [comment]
It's along the lines of "cant verify your account, account has been
verified. Im not sure whats causing this the 3 accounts log in no problem
even with captcha but the 4th one starts causing problems.

čet, 14. ruj 2023. u 07:04 shupershuff ***@***.***> napisao
je:
