### ISSUE TITLE
Not an issue but to say thank you!

### ISSUE THREAD

**Issue by AquaRush** [shupershuff/Diablo2RLoader#21]
Hey, @shupershuff

**_*THIS IS NOT AN ISSUE, JUST TO SHOW GRATITUDE!*_**

Thanks for this amazing repo that you've made, amazing quality code, comments for modifying it and overall performance.

Wish you all the best, cheers!

**Comment by shupershuff** [comment]
Cheers mate! Appreciate it. Very cool to have strangers across the world find some use in my wee project :)
