### ISSUE TITLE
Worked the first time when loading one character

### ISSUE THREAD

**Issue by jermely** [shupershuff/Diablo2RLoader#22]
Hi there,

Thanks for the work. When first setting it up and launching it, I just went in with my #1 acc. It worked. I then tried tabbing to the loader to open #2. That one "timed-out" when connecting to battlenet sending me to the offline screen. The issue isn't the one of "wrong credentials" because now my #1 does the same (the one I already got in-game with on its own).

Tried launching it through the bnet client, it asked for a capcha and ten the regular way worked.

The loader-way, even with 1 or 2 acc's, doesn't. Is this just a matter of temp ban/cool-off period for logging in without the client?

**Comment by jermely** [comment]
It works now. Probably needed cooling off.

**Comment by shupershuff** [comment]
It seems for some people it sometimes asks for Captcha codes. I don't recall ever having to have done one so not too sure what causes it.

In a slightly related noted, I have noticed when there's too many failed authentication attempts to a particular region then you can get a temporary lock out for a short period of time. During which, you can't connect in with any account.
