### ISSUE TITLE
Is there a set way to open a windowed account on a specific spot?

### ISSUE THREAD

**Issue by jermely** [shupershuff/Diablo2RLoader#23]
For instance, I run a dual monitor setup. I play HC. So having my BO barb up in a windowed mode on the 2nd monitor is how I do my sheeez.

Can it be automated to launch there? Maybe by pixel, so you can place it yourself?

I'm sorry if there's a better place for suggestions.

**Comment by shupershuff** [comment]
I've been having a look tonight and I can't see anyway to modify the launch location of this app. It's not possible via settings.json, I can't see any settings in registry that can be tinkered with and there's no documented launch flags that can be used.
So it doesn't look like there is a way sorry.
Perhaps a 3rd party app such as this might help: https://www.desksoft.com/WindowManager.htm
