### ISSUE TITLE
Issue with windows 11?

### ISSUE THREAD

**Issue by bmml1** [shupershuff/Diablo2RLoader#24]
Hello,

I use the script on my main rig with windows 10 and on a notebook with windows 11. 
On the main rig it works just fine. on the notebook with windows 11 it starts the first instance but trying to open the second one results in the script just tabbing into the first one and doing nothing.

I think it used to work under windows 11 before but i tried back to version 1.8.1 with no success.

You got any idea?

BR

**Comment by shupershuff** [comment]
I'll create a Windows 11 VM and test later on. 

I have heard there are issues in Windows 11 with handle64 and procexp not being able to kill the process handle. Not sure on the details. If it's related to that then there's probably not much I can do.

I have heard that disabling memory integrity can help, I'm skeptical but you can give it a try, info from microsoft here:
https://support.microsoft.com/en-us/windows/a-driver-can-t-load-on-this-device-8eea34e5-ff4b-16ec-870d-61a4a43b3dd5

**Comment by shupershuff** [comment]
Got a VM stood up but I can't actually download the bnet client right now, the site they rely on for downloads seems to be broken. :(

**Comment by shupershuff** [comment]
Ugh, seems there's no VM driver to actually run the game so I can't fully test, I do notice that when the script is opening d2r.exe that the handle is being killed by the script so that part does seem to be working in that respect (at least for me). 
Can you please launch an account and use procexp to confirm that the handle is indeed not running?

**Comment by bmml1** [comment]
1) disabling memory integrity did not help
2) the handle is successfully killed after the start of the first instance

**Comment by bmml1** [comment]
I started the first instance with loader and created a manual shortcut with user/pw/address command line arguments to start a second instance. It lead to the same result(so just tabbing into the first open instance)

So there seems to be something strange with opening the d2r.exe again on windows 11.

**Comment by shupershuff** [comment]
> I started the first instance with loader and created a manual shortcut with user/pw/address command line arguments to start a second instance. It lead to the same result(so just tabbing into the first open instance)
> 
> So there seems to be something strange with opening the d2r.exe again on windows 11.

What happens if you open both instances with shortcuts?

**Comment by bmml1** [comment]
It worked.

Now I tried again with loader and it worked too. I think we can close the issue.

**Comment by shupershuff** [comment]
hmm. Might keep it open for a bit and keep it under observation.
I'm still going to try test on a windows 11 machine when I can.

**Comment by shupershuff** [comment]
Managed to setup a VM via Hyper-V as VMware Workstation doesn't allow for GPU partitioning/sharing.
Anywho, I couldn't replicate this issue.

**Comment by oers** [comment]
worked for me, after other methods stopped working on windows 11

**Comment by Mongrelix** [comment]
I can't seem to get it working on windows 11 anymore. all my accounts now goto offline mode.

**Comment by shupershuff** [comment]
> I can't seem to get it working on windows 11 anymore. all my accounts now goto offline mode. Seems that the authenticator on one of the accounts was causing issues.

Unfortunately the method used to open the game (launch d2r.exe with parameters) does not work with Authenticator.

**Comment by shupershuff** [comment]
Going to close this issue off for now.

I will note that for @Mongrelix's issue, the latest version of the script is capable of working with accounts with MFA enabled now (MFA enabled accounts will require you to configure the authentication token).
