### ISSUE TITLE
Function to kill open handles

### ISSUE THREAD

**Issue by oers** [shupershuff/Diablo2RLoader#26]
I would like to just have a plain function call like 'k'
which kills all open handles
 I have one account I have to sign in manually due to 2fa
 and afterwards I want to start the other account 
 when I start manually and then start 1 in the script
, it will not kill all open handles before launching 1

**Comment by shupershuff** [comment]
I had someone else ask me this yesterday too. I will have something for this in the next update. For now, as a quick workaround, open the ps1 file and on line 1645 type killhandle

**Comment by shupershuff** [comment]
I have built and tested a capability to check for existing handles when launching from the script.
The new version will also ensure that the correct window is renamed.

**Comment by shupershuff** [comment]
Resolved in v1.10.0 script now looks to kill handles prior to launching another instance.
