### ISSUE TITLE
Doesn't work on Asia server

### ISSUE THREAD

**Issue by arithxp** [shupershuff/Diablo2RLoader#27]
It doesn't work on Asia server
Is there any solution?

US and EU servers work well.

**Comment by shupershuff** [comment]
Not a script issue, Blizzards auth servers crapped out again.
Nothing I can do sorry but wait for them to fix. It happens sometimes and they're painfully slow at resolving, this is the longest I've seen a region down for.

**Comment by arithxp** [comment]
I will use the Battle.net launcher until the server down is resolved.
thank you for the reply.
