### ISSUE TITLE
Issues with the Asia server

### ISSUE THREAD

**Issue by loodakrawa** [shupershuff/Diablo2RLoader#28]
Hi, first of all - great script. Helps so much with multiple instances.

The problem:
Connecting to the Asia server doesn't work. After the game starts, it tries to connect to battle.net and it says "cannot connect to server". If run from the official Battle.net app it works fine. Some people on various Discord groups mentioned that other similar scripts don't work either so it's likely something on Blizzard's end. Not sure if anything can be done from the script itself but reporting just in case.

**Comment by shupershuff** [comment]
Thanks for reporting. Yes it's an issue at Blizzards end that I can't control unfortunately.
Not the first time it's happened and not the last, to my knowledge this is the longest outage there's been for authentication being down in one of their realms.
I'm looking into configurable alternative authentication methods.

In the meantime I recommend launching all but one of your accounts on another region. Use battlenet to launch the last instance on Asia (KR), Use the instance launched via bnet to make Asia games, then use friend joining to join KR games.

Keep this issue open until auth issues are resolved as others will also likely come here looking for info, cheers!

**Comment by shupershuff** [comment]
Great news everyone!
With the help of people much smarter than me, I have a solution to resolve this utilising authentication tokens that will be in the next release. This should also work with MFA enabled accounts.

There will be an additional config option to choose between using traditional username and PW to authenticate via parameters or to alternatively authenticate via a Token (essentially what happens when you open the game from the battlenet client).
Also looking at building in an outage notification mechanism and an additional NextTZ source.

It will be a few days for me to build, test, test, test again and release.
Chaos, Tomb and WSK TZ's slow down my script dev progress in my free time :)

**Comment by shupershuff** [comment]
Resolved in new release. Setup steps must be performed, see release notes and setup instructions on readme.

**Comment by Edgar-Huynh** [comment]
> Resolved in new release. Setup steps must be performed, see release notes and setup instructions on readme.

Hi [shupershuff](https://github.com/shupershuff). Thank you for supporting us, D2R lovers.
I'm the owner of the issue proposed in the Blizzard Forum [Technical Support] below.
Thanks for the reply. We appreciate your help a lot, adding Token Authentication is a step forward to live with Blizzard corruption...

[Cannot login to Asia/Korea server via Shortcut (bypass Battle net App) after October 6th 2023](https://us.forums.blizzard.com/en/d2r/t/cannot-login-to-asiakorea-server-via-shortcut-bypass-battle-net-app-after-october-6th-2023/162650)

**Comment by rushing01** [comment]
Love the script! One question how can you force it to use token when you have it going through parameters? I know you mentioned it but i can't find how to do in the info screen unless im blind. Had an issue this morning trying to log into asia and kept giving me error for dcloen

**Comment by shupershuff** [comment]
> Love the script! One question how can you force it to use token when you have it going through parameters? I know you mentioned it but i can't find how to do in the info screen unless im blind. Had an issue this morning trying to log into asia and kept giving me error for dcloen

Thanks for the feedback!
It's currently toggleable within the Info screen. I might do a wee update to remove this and instead have a config option to force AuthToken on specified regions. IE allow you to configure to use Parameters to connect to EU, NA and use Tokens to connect to KR.
