### ISSUE TITLE
How to kill a cow king?

### ISSUE THREAD

**Issue by subaridji** [shupershuff/Diablo2RLoader#34]
Question for everybody, except the author:
![image](https://github.com/shupershuff/Diablo2RLoader/assets/28545861/99067bc8-b645-47d4-897e-178567ef7110)

**Comment by shupershuff** [comment]
:)
You have .024% of getting a perfect gem and 0.41% chance of killing the Cow King when enabling/disabling gibbering gem (AKA chat gem).
Successfully activating either will raise your script MF. Unlike the game, increasing MF in the script will increase your chances of finding HR's.

Of which, by default there's a 0.005% chance of finding a High Rune from the quote rolls. I've somehow found 3 HR's out of 67,362 items.
I've also launched the script 1930 times (and that excludes a lot of testing launches)!

Bit of a silly feature but thought it would be a fun thing to add for an RNG game :D
Happy hunting!
