### ISSUE TITLE
TZ and Dclone updates fail with d2emu.com

### ISSUE THREAD

**Issue by subaridji** [shupershuff/Diablo2RLoader#36]
Seems like source have updated, so tz and dclone requests time out.
![image](https://github.com/shupershuff/Diablo2RLoader/assets/28545861/9ff39754-e962-4b3f-9456-49f213debd4f)
![image](https://github.com/shupershuff/Diablo2RLoader/assets/28545861/31000e5e-bd7e-4f2a-9d59-945326a5a1c3)
![image](https://github.com/shupershuff/Diablo2RLoader/assets/28545861/14f89b8f-6cc7-42a4-ae7d-4db232bb6724)

**Comment by shupershuff** [comment]
Perhaps it had a bit of an outage? Just checked it now and it seems to be functioning normally.
