### ISSUE TITLE
Error page to get token doesn't work; here's an alternative

### ISSUE THREAD

**Issue by pintomau** [shupershuff/Diablo2RLoader#42]
Hey.

I kept getting stuck with the token part.

The guide mentions that we'll get redirected to some error page from which we can get a token.

This never happened for me with both Firefox or Edge, Incognito.

The alternative that worked for me is:
1. Open the page in incognito mode (used "eu" instead of "us", but that should be a detail)
2. Turn on developer tools and switch to the Network tab
3. Login
4. Getting an error in the `/login/en/?externalChallenge=login` page
5. Open the Response Cookies for that request
6. Notice the `gs-osi` cookie with the `EU-.....` token value.

![image](https://github.com/shupershuff/Diablo2RLoader/assets/1271442/30f14d8b-fac7-4fb4-ab7c-7cdae4a1a8e5)

**Comment by shupershuff** [comment]
You're supposed to arrive on an error page that shows your token.
Do you get a different page than what's shown in the instructions?

**Comment by pintomau** [comment]
Hey. No redirect at all. Stuck at loading on login.

**Comment by shupershuff** [comment]
Can you provide a screenshot of what you're describing?
Also does this link work? https://eu.account.battle.net/login/en/?externalChallenge=login&app=OSI
It should bring you to a login page, after logging in you should see something like this:
![image](https://github.com/shupershuff/Diablo2RLoader/assets/63577525/865eaf11-3fe4-4e6c-a4bb-16aca53b6ce5)

**Comment by pintomau** [comment]
I've tried both eu and us.

It simply stays on the login form, in a loading state, like so:

![image](https://github.com/shupershuff/Diablo2RLoader/assets/1271442/9328d035-8b0d-4352-b88f-7d6f264b4596)

When inspecting the network, I see the error I mentioned above.

**Comment by shupershuff** [comment]
What region do you normally play on? Are you using a VPN?

**Comment by pintomau** [comment]
EU. No VPN.

Again, I'm not blocked. Found the alternative I described in the opening post.

Just wanted to share it in case someone gets stuck as I did.

**Comment by shupershuff** [comment]
Do you use a proxy server or anything like that?
Does the issue still happen? Just wondering if it's a one off, as this hasn't been reported before.

**Comment by pintomau** [comment]
No proxies.

It still happens.

If I do it on my mobile phone, it works, though.

**Comment by shupershuff** [comment]
Sounds like a one off issue, possibly related with your ISP if it's happening on your home internet connection but not mobile data connection. 
I've not had other reports of this issue before/since so I'm hoping it's a one-off thing.

Thanks for raising and thanks for troubleshooting and providing the workaround.
If I hear of any other issues like this I'll defer to your helpful findings here :)

Cheers!
