### ISSUE TITLE
Accounts.csv has duplicate IDs

### ISSUE THREAD

**Issue by maxbars1996** [shupershuff/Diablo2RLoader#43]
But id is different! 
![1](https://github.com/shupershuff/Diablo2RLoader/assets/70397379/e489e525-105b-4f0b-85f5-cc293e82e7fb)
![2](https://github.com/shupershuff/Diablo2RLoader/assets/70397379/2f5e0dfd-a9b5-459b-8043-f16924502969)

**Comment by shupershuff** [comment]
Something I've found with this software is, when you delete the rows (by selecting them and pressing delete), the rows are still actually there. Right click on the last couple empty rows and delete them:
![image](https://github.com/shupershuff/Diablo2RLoader/assets/63577525/c86f6017-e9bf-464e-9c95-336a3091bd84)

Note that this issue will be resolved in the next version as the script will check for blank rows in the csv file and remove them to remedy this mistake being made in the csv file.

**Comment by maxbars1996** [comment]
thx, it works!
