### ISSUE TITLE
[Feature request] Default region per-account in Account.csv

### ISSUE THREAD

**Issue by mrhappyasthma** [shupershuff/Diablo2RLoader#46]
**SUB-ISSUE 1:**
I like to have my accounts launch in different regions (so I can see all available games and easily join between regions for clone spawns or trades).

Specifically for 'batch' launch. But could be useful even for individually launching

**Comment by mrhappyasthma** [comment]
It would also be nice to optionally remove 'default region' to avoid launching without explicitly selecting a region in the tool. (e.g. if I hit enter twice too quickly it jumps to my default. But it may be nice to un-set this for some accounts)

**Comment by shupershuff** [comment]
> I like to have my accounts launch in different regions (so I can see all available games and easily join between regions for clone spawns or trades).
> 
> Specifically for 'batch' launch. But could be useful even for individually launching

I won't add a feature in for this as it would add complexity for other users. That said I do have some good news, I'll make it so you can make a batch script to launch these accounts using the scripts launch parameters. I just need to change a couple things as I've not updated the scripts launch parameter functionality since I added the ability to add tokens. Stay tuned :)

**Comment by shupershuff** [comment]
> It would also be nice to optionally remove 'default region' to avoid launching without explicitly selecting a region in the tool. (e.g. if I hit enter twice too quickly it jumps to my default. But it may be nice to un-set this for some accounts)

If it's not optional already, I will make it so that this can optionally be left blank.

**Comment by shupershuff** [comment]
For Sub-issue 1, I wasn't able to figure out a decent batch script to launch accounts in each region in a smart way that works with token authentication. If you're not using Token auth, then I can provide something for you.

For Sub-Issue 2, as stated above, default region can be left blank in the next version.
