### ISSUE TITLE
Weird window sizing error on initial startup

### ISSUE THREAD

**Issue by mrhappyasthma** [shupershuff/Diablo2RLoader#50]
I installed this on my laptop (the tool is amazing btw).

I get an error that flashed only for a few seconds:

![image](https://github.com/user-attachments/assets/743cdbd0-2070-45a9-a5b5-3ab7f9b8b1a6)

I couldn't find a setting for this in the xml so not sure what's the issue.

**Comment by shupershuff** [comment]
Can you replace Clear-Host in the script with #Clear-Host (ie comment it out), rerun and get a screenshot of the whole error?

**Comment by mrhappyasthma** [comment]
```
Exception setting "WindowHeight": "The value must be less than the console's current maximum window size of 45 in that
dimension. Note that this value depends on screen resolution and the console font.
Parameter name: height
Actual value was 50."
At C:\Users\Mark\Documents\GitHub\Diablo2RLoader\D2Loader.ps1:85 char:1
+ [console]::WindowHeight=50; #Can be adjusted to preference, but not l ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
    + FullyQualifiedErrorId : ExceptionWhenSetting
```

Seems like this is a value we could adjust in the script, but maybe could be in the XML? (e.g. replace `::windowheight = 50` with something smaller)

**Comment by shupershuff** [comment]
> ```
> Exception setting "WindowHeight": "The value must be less than the console's current maximum window size of 45 in that
> dimension. Note that this value depends on screen resolution and the console font.
> Parameter name: height
> Actual value was 50."
> At C:\Users\Mark\Documents\GitHub\Diablo2RLoader\D2Loader.ps1:85 char:1
> + [console]::WindowHeight=50; #Can be adjusted to preference, but not l ...
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [], SetValueInvocationException
>     + FullyQualifiedErrorId : ExceptionWhenSetting
> ```
> 
> Seems like this is a value we could adjust in the script, but maybe could be in the XML? (e.g. replace `::windowheight = 50` with something smaller)

I had considered putting it in XML but have tried to reduce complexity for end users (even editing an XML is overwhelming for some).

I'm surprised that whatever this is running on can't run it at 50 height. I had laptop users in mind when making this.
What is the screen resolution?

**Comment by mrhappyasthma** [comment]
It seems to be an issue if you have the `Scale` increased in your display settings:

![image](https://github.com/user-attachments/assets/e8421041-f8ad-4808-950a-0e91fb10da2d)

I confirmed it would work properly if the scale is not set. Perhaps we need to read this value from the system and adjust the values appropriately.

**Comment by shupershuff** [comment]
Hmm, yea it wasn't designed to work on such a huge zoom. As a quick fix, change the line:
`[console]::WindowHeight=50  #Can be adjusted to preference, but not less than 42`
to this:
```
$WindowHeight=50 #Can be adjusted to preference, but not less than 42
do {
	Try {
		[console]::WindowHeight=$WindowHeight;
		$HeightSuccessfullySet = $True
	}
	Catch {
		$WindowHeight --
	}
} Until ($HeightSuccessfullySet -eq $True)
```

This means if it fails to set the height to due resolution or scale, it'll keep trying a smaller height until it doesn't error.

**Comment by shupershuff** [comment]
The above fix will be in the next release
