### ISSUE TITLE
Couldn't get D2Emu connection Token.

### ISSUE THREAD

**Issue by hebjor** [shupershuff/Diablo2RLoader#51]
Hi & thanks for a great tool,

I'm using version 1.13.2

![image](https://github.com/user-attachments/assets/c2422325-9495-485c-bbeb-1e8c58c0c6af)

Recently I started to get this message when I start 

![image](https://github.com/user-attachments/assets/265cb7eb-d052-46d4-a504-690e22f51d6d)

I tried all 3 different sites (d2emu.com, D2runewizard.com and diablo2.io) but get same error message with all of them.

When I do a "r" to refresh I keep getting "Unable to check for DClone status via d2emu.com."
When I do a "d" to check DClone status I get these error messages

![image](https://github.com/user-attachments/assets/8a94afcb-dd69-47f9-884c-1ad20babc17e)

Connecting to d2emu.com website works fine in a browser.  I'm connecting from Thailand/Asia.

**Comment by shupershuff** [comment]
Can you reopen script, try again and let me know if it still happens?

**Comment by hebjor** [comment]
Yes, same issue

----
`Friday, September 13, 2024 9:30:45 PM

PS D:\games\D2RLoader> .\D2Loader.ps1
 Couldn't get D2Emu connection Token.
  Press any key to continue...`

**Comment by shupershuff** [comment]
Are you able to get to the d2emu website?
https://d2emu.com/

**Comment by hebjor** [comment]
Yes, website works fine.  I use it for checking TZ and never had any issues with it.

The first command returns a blank line, the 2nd seem to return nothing.
![image](https://github.com/user-attachments/assets/b6302e74-744a-46ac-96a0-b33e8fcd35d5)

**Comment by shupershuff** [comment]
That's really odd. What do you get when you simply run the following:

```invoke-webrequest https://d2emu.com/api/v1/shupertoken/aes```
```invoke-webrequest https://d2emu.com/api/v1/shupertoken/token```

Are you using your own internet connection? Wondering if the connection is being blocked via a proxy or firewall.

**Comment by hebjor** [comment]
![image](https://github.com/user-attachments/assets/f0f357b8-46a9-417f-9cc1-8b5f46bff28d)

Yes, it is my own internet.  It is 1000/1000 fiber and as far as I know there are no restrictions (firewall or proxy).  As far as I can tell this is just normal https traffic.  Could it be d2emu.com is using some kind of Cloudflare caching that causes this?

**Comment by hebjor** [comment]
I tried to remote desktop into my computer back in Europe and get different results that seem to make more sense.  I will install a VPN and do some more testing from Thailand.  It seems the Thailand internet connection is the issue.

![image](https://github.com/user-attachments/assets/97fdbe40-ec82-4854-b77b-421bcbcf35c1)

**Comment by shupershuff** [comment]
It's definitely an internet connection / firewall issue as there aren't any issues with D2Emu's API.
That said, I'll reach out to him to see if there's any geo blocking going on.

**Comment by hebjor** [comment]
Yeah, this is very strange.  I installed NordVPN and tried from both Singapore and US but get the same empty results.  It makes me wonder if it could be something local on my computer.  It's kinda weird since it is fresh Windows 11 install.  I have disabled Windows Defender and Windows Firewall. I will do some more testing in my end, and see if I can install it on an old Windows laptop.

**Comment by shupershuff** [comment]
What about another URL, does this return no content?

```Invoke-webrequest -uri https://v2.jokeapi.dev/joke/miscellaneous```

**Comment by shupershuff** [comment]
Also, try this command
```Invoke-WebRequest -Uri "https://d2emu.com/api/v1/shupertoken/aes" -Proxy $null```

**Comment by hebjor** [comment]
![image](https://github.com/user-attachments/assets/44b6b6d9-c4b3-4036-92d1-d8c9b92a2cb1)

It worked!  So there must be some sort of proxy somewhere.  I also tried the previous commands on a Windows 10 laptop I have and it also works.  So this must be some local problem on my new pc.

**Comment by hebjor** [comment]
The jokeapi works without the proxy parameter

![image](https://github.com/user-attachments/assets/d828a717-3a74-46af-af6b-e5bc7aa17c02)

**Comment by hebjor** [comment]
Clearly a local problem on this Windows 11 pc, but I have no idea where that proxy comes from.  When I run some commands to check it does not report any proxy.

![image](https://github.com/user-attachments/assets/5e87674f-e4ce-4c0c-b692-8660b926a30f)

**Comment by shupershuff** [comment]
You can also use this to check proxy
```Get-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings'```

Or open "internet options" from start menu (the old menu you might recognise from Internet Explorer back in the day)

**Comment by hebjor** [comment]
This is very weird, now it actually works without the -Proxy too. 
![image](https://github.com/user-attachments/assets/b9ab4143-e4a6-4168-a188-aebaf8e15ffe)
Also D2Rloader starts and works just fine.  
![image](https://github.com/user-attachments/assets/c71fcba4-058c-4c3d-b814-d25d3dbfb028)

I have no idea what is going on here,  but I'm very happy it works!  Thanks so much for the help

**Comment by shupershuff** [comment]
Glad to hear :)

**Comment by hebjor** [comment]
Not understanding what was wrong drove me crazy so I did some more testing, and it seems to be the version of PS that caused the issue.

Powershell 7.4.5 fails
![image](https://github.com/user-attachments/assets/4972141d-7037-41ea-b851-9fa63b6ac0d1)

Powershell 5.1.22621.4111 works
![image](https://github.com/user-attachments/assets/595f2c3d-9045-42e9-af56-3378c523de92)

![image](https://github.com/user-attachments/assets/9642189c-52de-45f0-9fad-1652f8c7b4d4)
![image](https://github.com/user-attachments/assets/c8db8d26-7d23-4043-ade5-3390b3b81270)

also the -Proxy parameter does not seem to make any difference, it was just a random thing I started PS via CMD I got the older version.  I normally start it via Windows Terminal which starts the lates version.
![image](https://github.com/user-attachments/assets/707c6d23-a99b-4757-af4a-e0bdf8e973e5)

**Comment by shupershuff** [comment]
> Not understanding what was wrong drove me crazy so I did some more testing, and it seems to be the version of PS that caused the issue.
> 
> Powershell 7.4.5 fails ![image](https://private-user-images.githubusercontent.com/152973807/367558272-4972141d-7037-41ea-b851-9fa63b6ac0d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTAyMDEsIm5iZiI6MTcyNjQwOTkwMSwicGF0aCI6Ii8xNTI5NzM4MDcvMzY3NTU4MjcyLTQ5NzIxNDFkLTcwMzctNDFlYS1iODUxLTlmYTYzYjZhYzBkMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNDE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGU3NTIwMDI0ODJjZWIzMDQyYzYzNjZhZGM2NmY3YTgwZDBjYjRhZDgyZTRhOTM0N2IyMzFiZTc4MDhkNDIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.B4tzDe4w8CI7XCIeAdGZPHMjECI8sHXufq4KTBFKJDc)
> 
> Powershell 5.1.22621.4111 works ![image](https://private-user-images.githubusercontent.com/152973807/367558533-595f2c3d-9045-42e9-af56-3378c523de92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTAyMDEsIm5iZiI6MTcyNjQwOTkwMSwicGF0aCI6Ii8xNTI5NzM4MDcvMzY3NTU4NTMzLTU5NWYyYzNkLTkwNDUtNDJlOS1hZjU2LTMzNzhjNTIzZGU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNDE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMzM1NjczNzk0YTA2OWU4ZTQ4NWE5OWIwM2IwNDBlNzVkZmIyY2VhNWExNjAxNTRjNThiZGI0ZjU3MjEwMmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.X9EPWXGSKKh8CogWcvTAL4qNYMgiFpeSA2L7fqrFQVI)
> 
> ![image](https://private-user-images.githubusercontent.com/152973807/367558857-025e8d91-0864-4535-b3de-43ef956c9862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTAyMDEsIm5iZiI6MTcyNjQwOTkwMSwicGF0aCI6Ii8xNTI5NzM4MDcvMzY3NTU4ODU3LTAyNWU4ZDkxLTA4NjQtNDUzNS1iM2RlLTQzZWY5NTZjOTg2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNDE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04Zjc4MmYyN2IxZDA4OTBjMjViMGEwZDc3NDEyOWUzYzQzNTZlOWU2YTMzMzNlMjNjNGVhYmJlZDU0M2JjMDIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hUsZo9mJ1zL6K-ZD064uqNbfnf9nMQ1p-gsP7kFuUV0) ![image](https://private-user-images.githubusercontent.com/152973807/367558653-c8db8d26-7d23-4043-ade5-3390b3b81270.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTAyMDEsIm5iZiI6MTcyNjQwOTkwMSwicGF0aCI6Ii8xNTI5NzM4MDcvMzY3NTU4NjUzLWM4ZGI4ZDI2LTdkMjMtNDA0My1hZGU1LTMzOTBiM2I4MTI3MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNVQxNDE4MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjJiNjUwY2I0ZTk2M2VjNTM0ZDdkOTI1OGQxYzQ3MGQ0YWNmOTY4NTFiMWJjYTMzOGI3MDg4YzYzNGE1N2FjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0GgH-IsqXqPhNVtShslCqGreps3bzcIxymBh0Dzk9Wk)
> 
> also the -Proxy parameter does not seem to make any difference, it was just a random thing I started PS via CMD I got the older version. I normally start it via Windows Terminal which starts the latest version.

Thanks for the details mate. I will have a think about how I can prevent this happening going forward.

**Comment by shupershuff** [comment]
I've not been able to figure out the connection problems. It also happens with curl and invoke-restmethod when connecting to that site. It's likely an issue with cloudflare or the webserver.
As a workaround, try replacing the GetEmuToken Function with the below, this will force PS 7 to run those commands in PS 5.1:

```
Function GetEmuToken { #For connecting to D2Emu for tz and/or dclone data
	Try {
		if ($PSVersionTable.psversion.major -ge 7 -or $true -eq $True){# Run a PowerShell 5.1 script from within PowerShell 7.x, for whatever reason no content is returned on PS 7.x. Identified in https://github.com/shupershuff/Diablo2RLoader/issues/51
			$AES = & "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -Command {(invoke-webrequest https://d2emu.com/api/v1/shupertoken/aes).content | convertfrom-json}
			$EncryptedToken = & "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -ExecutionPolicy Bypass -Command {((invoke-webrequest https://d2emu.com/api/v1/shupertoken/token).content | convertfrom-json).token}
		}
		Else {
			$AES = (invoke-webrequest https://d2emu.com/api/v1/shupertoken/aes).content | convertfrom-json
			$EncryptedToken = ((invoke-webrequest https://d2emu.com/api/v1/shupertoken/token).content | convertfrom-json).token
		}
		$Key = $AES.key
		$IV = $AES.iv
		$bytes = [System.Convert]::FromBase64String($EncryptedToken);
		$aes = [System.Security.Cryptography.Aes]::Create();
		$utf8 = [System.Text.Encoding]::Utf8;
		$aes.Key = $utf8.GetBytes($key);
		$aes.IV  = $utf8.GetBytes($iv);
		$decryptor = $aes.CreateDecryptor();
		$unencryptedData = $decryptor.TransformFinalBlock($bytes, 0, $bytes.Length);
		$aes.Dispose();
		$Script:EmuToken = [System.Text.Encoding]::UTF8.GetString($unencryptedData); #Decrypted token
	}
	Catch {
		write-output " Couldn't get D2Emu connection Token." | red
		PressTheAnyKey
	}
}
```

**Comment by hebjor** [comment]
I can confirm the GetEmuToken function above works on latest Powershell version.
