### ISSUE TITLE
Custom game settings are not being read for manual settings switcher.

### ISSUE THREAD

**Issue by subaridji** [shupershuff/Diablo2RLoader#52]
`if ($Script:AskForSettings -eq $True){#steps go through if user has toggled on the manual setting switcher ('s' in the menu).
$SettingsProfilePath = ("C:\Users\" + $Env:UserName + "\Saved Games\Diablo II Resurrected\")
$SettingsJSON = ($SettingsProfilePath + "Settings.json")`

$SettingsProfilePath needs a little update to be able to read from mod directory given in accounts.csv.

Great job with updating project (auto windows rearrange is just awesome)!

**Comment by shupershuff** [comment]
Hmm it should be already. After the code posted it then checks if customlauncharguments contains "-mod", if so, it then checks modinfo.json for a custom savepath for settings.

Can you please post details about the mod you're using, the launch argument used and the contents of modinfo.json and I can investigate further.

**Comment by shupershuff** [comment]
Closing due to no response

**Comment by shupershuff** [comment]
I think I've just realised what you meant sorry. Should have this fixed in the next release.
