### ISSUE TITLE
Stuck in connecting to Battle.net

### ISSUE THREAD

**Issue by elugo-jnj** [shupershuff/Diablo2RLoader#6]
Hi, I have followed all the steps, but cannot connect to Battle.net.

![1](https://github.com/shupershuff/Diablo2RLoader/assets/99763269/1b67727c-f814-4aa8-969b-f2efe4283efa)

**Comment by elugo-jnj** [comment]
I have accepted the authenticator requests, but I cannot connect.

![2](https://github.com/shupershuff/Diablo2RLoader/assets/99763269/726e1230-d067-4077-b225-0963394451a5)

**Comment by elugo-jnj** [comment]
I tried with an account without an authenticator and I was able to log in.

**Comment by shupershuff** [comment]
> It also appears that your script cannot encrypt passwords that have an @ in them.

One of the passwords I use has a @ in it and this works fine, keen to understand what's happening here.

**Comment by shupershuff** [comment]
> I have accepted the authenticator requests, but I cannot connect.
> 
> ![2](https://user-images.githubusercontent.com/99763269/240018952-726e1230-d067-4077-b225-0963394451a5.png)

Unfortunately even without this script having 2FA does not work when launching the game directly (not using the bnet client). There's not much I can do about this as this is a Blizzard issue :(

**Comment by elugo-jnj** [comment]
> > It also appears that your script cannot encrypt passwords that have an @ in them.
> 
> One of the passwords I use has a @ in it and this works fine, keen to understand what's happening here.

I can share the exact error, but it's in Spanish.

**Comment by shupershuff** [comment]
> > > It also appears that your script cannot encrypt passwords that have an @ in them.
> > 
> > 
> > One of the passwords I use has a @ in it and this works fine, keen to understand what's happening here.
> 
> I can share the exact error, but it's in Spanish.

Yes please, if you can show the error that'd be great.

**Comment by shupershuff** [comment]
Closing as it's been a week since the last response and I don't believe there's an issue with the script here.
Good luck hero.
