### ISSUE TITLE
failing switching to account settings

### ISSUE THREAD

**Issue by subaridji** [shupershuff/Diablo2RLoader#7]
1. 3 accounts, id-name: 1-master, 2-slave, 3-slave2
2. place 4 settings.json to ANYMOD game directory: settings.json, settings1.json (resolution scale 100), settings2.json (resolution scale 50), settings3.json (resolution scale 50)
3. additional game launch attributes: 
`$arguments = (" -username " + $script:acct + " -password " + $script:PW +" -address " + $Script:Region + " -mod ANYMOD -txt -enablerespec ").tostring()`
4. enable setting choice option in script cfg.
5. run script. i'm selecting acc 1 (master), getting prompt that setting file is being used from acc 3 (slave2), while actual settings are from last closed game (for ex. resolution scale set to 100).
6. run script. i'm selecting acc 2 (slave), getting prompt that setting file is being used from acc 3 (slave2), while actual settings are from last closed game (for ex. resolution scale set to 100)
![image](https://github.com/shupershuff/Diablo2RLoader/assets/28545861/bf09e4e5-c1b0-4d4c-ac61-eca590382da3)

**Comment by subaridji** [comment]
found, to run with mod in ANYMOD folder, modify settings string:
$SettingsProfilePath = ("C:\Users\" + $env:UserName + "\Saved Games\Diablo II Resurrected\mods\ANYMOD\")

**Comment by subaridji** [comment]
while prompt is always showing last account name settings being used. weird.

**Comment by shupershuff** [comment]
> 


> while prompt is always showing last account name settings being used. weird. smth wrong in $id.accountlabel

Good spotting, I didn't realise this, will try and get this fixed

**Comment by shupershuff** [comment]
Fixed the incorrect label display in the latest issue. It was always showing the very last account from your accounts.csv.
Sounds like you've self resolved the settings issue with your modded config :)

**Comment by shupershuff** [comment]
Will also be adding an option for custom CMD arguments in the next release so that you can edit the config file and not the script :)
