### ISSUE TITLE
great job with TZ tracker

### ISSUE THREAD

**Issue by subaridji** [shupershuff/Diablo2RLoader#8]
especially with parcing shitty site's pages.
but why don't use API instead?
check it out:
https://d2runewizard.com/integration

`{"terrorZone":{"zone":"Blood Moor and Den of Evil","act":"act1","lastReportedBy":{"displayName":"Hazel-rah","uid":"811795758"},"lastUpdate":{"seconds":1685112700,"nanoseconds":58000000},"reportedZones":{"Blood Moor and Den of Evil":9},"highestProbabilityZone":{"zone":"Blood Moor and Den of Evil","act":"act1","amount":9,"probability":1}},"providedBy":"https://d2runewizard.com/terror-zone-tracker"}`

**Comment by shupershuff** [comment]
It's definitely quite rough and slow, outside of the GitHub update check it's the first time I've tried to do something like this so I'm open to any suggestions! 
I was thinking I will pull current TZ from that site instead in the next update. What that d2runewizard doesn't have yet is predictions of the next TZ.

**Comment by shupershuff** [comment]
Current TZ will be pulled from d2runewizard the next release. Next TZ will continue to be pulled from Korean forum as the owner of d2runewizard has indicated that he doesn't intend on adding Next TZ to his site.
